config/routes.rb
Rails.application.routes.draw do
  resources :wikis 
  resources :charges, only: [:new, :create, :destroy]

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'about' => 'welcome#about'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class ="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to 'Wikis', wikis_path, :class => 'navbar-link' %></li>
      <li><%= link_to 'New Wiki', new_wiki_path, :class => 'navbar-link' %></li>


      <div class="pull-right" style="padding-top: 10px;">

      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %> <%= current_user.get_role %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>

      <% if user_signed_in? && current_user.standard? %>
        - <%= link_to 'Upgrade Account', new_charge_path, :class => 'navbar-link' %>
      <% else %>
        - <%= link_to 'Downgrade Account', new_charge_path, :class => 'navbar-link' %>
      <% end %>
      </div>

    </ul>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
<%= yield %>
  </div>




</body>
</html>